title:  Floris Jousselin
description: My site

theme: null

# github:
#   repo: robotcopper/robotcopper.github.io
#   branch: gh_page

readme_index:
  with_frontmatter: true

source              : .
destination         : config/_site
collections_dir     : config
layouts_dir         : config/_layouts
includes_dir        : config/_includes
sass:
  sass_dir: config/_sass

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

markdown: kramdown
highlighter: rouge
